# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('correct', models.IntegerField()),
                ('tries', models.IntegerField()),
            ],
        ),
    ]
