# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20180116_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
