# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_user_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(default='', null=True),
        ),
    ]
