# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_user_ds'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
